import * as StardewValley from '../assets/stardewvalley/index';
import { CardThemes } from '../types/gameSettings';
import defaultBG from '../assets/defaultBG.svg';

export const cardThemes = {
  SET_ONE: {
    name: '🚀✨Shapes and color🚀✨',
    cardBackround: defaultBG,
    cards: [
      {
        backgroundImage: 'linear-gradient(135deg, #FF5733, #FFC300)',
        icon: 'truck',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(200deg, #33FF57, #33FFC3)',
        icon: 'airplay',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(75deg, #3357FF, #57FFC3)',
        icon: 'lamp',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(160deg, #FF33A6, #FF57A6)',
        icon: 'arrowRight',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(120deg, #FF5733, #FF33C3)',
        icon: 'bell',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(230deg, #57FF33, #5733FF)',
        icon: 'camera',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(190deg, #33FF57, #33A6FF)',
        icon: 'cloud',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(80deg, #A633FF, #57FF33)',
        icon: 'coffee',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(250deg, #FF33FF, #FF33A6)',
        icon: 'compass',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(95deg, #5733FF, #FF5733)',
        icon: 'dollarSign',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(310deg, #33FFC3, #A633FF)',
        icon: 'edit',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(275deg, #FF57A6, #33FFC3)',
        icon: 'eye',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(130deg, #FF5733, #3357FF)',
        icon: 'heart',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(60deg, #FFC300, #FF33FF)',
        icon: 'home',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(215deg, #33FF57, #FF57A6)',
        icon: 'key',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(290deg, #FF5733, #33A6FF)',
        icon: 'lock',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(180deg, #33FFC3, #5733FF)',
        icon: 'map',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(55deg, #33FF57, #FF33A6)',
        icon: 'music',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(145deg, #FF33FF, #33FFC3)',
        icon: 'phone',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(170deg, #5733FF, #FF33A6)',
        icon: 'search',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(225deg, #FF5733, #FF57A6)',
        icon: 'settings',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(240deg, #33FF57, #3357FF)',
        icon: 'shoppingBag',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(330deg, #FF33C3, #33FFC3)',
        icon: 'star',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(205deg, #FF5733, #33A6FF)',
        icon: 'sun',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(100deg, #33FF57, #FF33FF)',
        icon: 'thumbsUp',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(285deg, #FF57A6, #33FFC3)',
        icon: 'user',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(345deg, #5733FF, #FF33C3)',
        icon: 'watch',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(195deg, #FF5733, #FF33A6)',
        icon: 'wifi',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(150deg, #33FF57, #5733FF)',
        icon: 'x',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(300deg, #33FFC3, #FF57A6)',
        icon: 'zoomIn',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(45deg, #FF7F50, #FFD700)',
        icon: 'thumbsDown',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(135deg, #1E90FF, #00BFFF)',
        icon: 'wind',
        isMatched: false,
        isFlipped: false,
      },
    ],
  },
  SET_TWO: {
    name: '👩‍🌾Stardew Valley👨‍🌾',
    cardBackround: defaultBG,
    cards: [
      {
        backgroundImage: StardewValley.Abigail,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Alex,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Caroline,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Clint,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Demetrius,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Dwarf,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Elliott,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Emily,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Evelyn,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.George,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Gus,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Haley,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Harvey,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Jas,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Jodi,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Kent,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Krobus,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Leah,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Leo,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Lewis,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Linus,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Marnie,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Maru,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Pam,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Penny,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Pierre,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Sam,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Sandy,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Sebastian,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Shane,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Vincent,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Willy,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: StardewValley.Wizard,
        icon: '',
        isMatched: false,
        isFlipped: false,
      },
    ],
  },
} as CardThemes;
