import {
  TruckIcon,
  AirplayIcon,
  LampIcon,
  ArrowRightIcon,
  BellIcon,
  CameraIcon,
  CloudIcon,
  CoffeeIcon,
  CompassIcon,
  DollarSignIcon,
  EditIcon,
  EyeIcon,
  HeartIcon,
  HomeIcon,
  KeyIcon,
  LockIcon,
  MapIcon,
  MusicIcon,
  PhoneIcon,
  SearchIcon,
  SettingsIcon,
  ShoppingBagIcon,
  StarIcon,
  SunIcon,
  ThumbsUpIcon,
  UserIcon,
  WatchIcon,
  WifiIcon,
  XIcon,
  ZoomInIcon,
} from 'lucide-react';
import { CardThemes } from '../types/gameSettings';
import defaultBG from '../assets/defaultBG.svg';

export const cardThemes = {
  SET_ONE: {
    name: 'Set One',
    cardBackround: defaultBG,
    cards: [
      {
        backgroundImage: 'linear-gradient(135deg, #FF5733, #FFC300)',
        icon: <TruckIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(200deg, #33FF57, #33FFC3)',
        icon: <AirplayIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(75deg, #3357FF, #57FFC3)',
        icon: <LampIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(160deg, #FF33A6, #FF57A6)',
        icon: <ArrowRightIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(120deg, #FF5733, #FF33C3)',
        icon: <BellIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(230deg, #57FF33, #5733FF)',
        icon: <CameraIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(190deg, #33FF57, #33A6FF)',
        icon: <CloudIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(80deg, #A633FF, #57FF33)',
        icon: <CoffeeIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(250deg, #FF33FF, #FF33A6)',
        icon: <CompassIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(95deg, #5733FF, #FF5733)',
        icon: <DollarSignIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(310deg, #33FFC3, #A633FF)',
        icon: <EditIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(275deg, #FF57A6, #33FFC3)',
        icon: <EyeIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(130deg, #FF5733, #3357FF)',
        icon: <HeartIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(60deg, #FFC300, #FF33FF)',
        icon: <HomeIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(215deg, #33FF57, #FF57A6)',
        icon: <KeyIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(290deg, #FF5733, #33A6FF)',
        icon: <LockIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(180deg, #33FFC3, #5733FF)',
        icon: <MapIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(55deg, #33FF57, #FF33A6)',
        icon: <MusicIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(145deg, #FF33FF, #33FFC3)',
        icon: <PhoneIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(170deg, #5733FF, #FF33A6)',
        icon: <SearchIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(225deg, #FF5733, #FF57A6)',
        icon: <SettingsIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(240deg, #33FF57, #3357FF)',
        icon: <ShoppingBagIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(330deg, #FF33C3, #33FFC3)',
        icon: <StarIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(205deg, #FF5733, #33A6FF)',
        icon: <SunIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(100deg, #33FF57, #FF33FF)',
        icon: <ThumbsUpIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(285deg, #FF57A6, #33FFC3)',
        icon: <UserIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(345deg, #5733FF, #FF33C3)',
        icon: <WatchIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(195deg, #FF5733, #FF33A6)',
        icon: <WifiIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(150deg, #33FF57, #5733FF)',
        icon: <XIcon />,
        isMatched: false,
        isFlipped: false,
      },
      {
        backgroundImage: 'linear-gradient(300deg, #33FFC3, #FF57A6)',
        icon: <ZoomInIcon />,
        isMatched: false,
        isFlipped: false,
      },
    ],
  },
} as CardThemes;
