import {
  TruckIcon,
  AirplayIcon,
  LampIcon,
  ArrowRightIcon,
  BellIcon,
  CameraIcon,
  CloudIcon,
  CoffeeIcon,
  CompassIcon,
  DollarSignIcon,
  EditIcon,
  EyeIcon,
  HeartIcon,
  HomeIcon,
  KeyIcon,
  LockIcon,
  MapIcon,
  MusicIcon,
  PhoneIcon,
  SearchIcon,
  SettingsIcon,
  ShoppingBagIcon,
  StarIcon,
  SunIcon,
  ThumbsUpIcon,
  UserIcon,
  WatchIcon,
  WifiIcon,
  XIcon,
  ZoomInIcon,
  ThumbsDownIcon,
  WindIcon,
} from 'lucide-react';

const iconMapping: Record<string, JSX.Element> = {
  truck: <TruckIcon />,
  airplay: <AirplayIcon />,
  lamp: <LampIcon />,
  arrowRight: <ArrowRightIcon />,
  bell: <BellIcon />,
  camera: <CameraIcon />,
  cloud: <CloudIcon />,
  coffee: <CoffeeIcon />,
  compass: <CompassIcon />,
  dollarSign: <DollarSignIcon />,
  edit: <EditIcon />,
  eye: <EyeIcon />,
  heart: <HeartIcon />,
  home: <HomeIcon />,
  key: <KeyIcon />,
  lock: <LockIcon />,
  map: <MapIcon />,
  music: <MusicIcon />,
  phone: <PhoneIcon />,
  search: <SearchIcon />,
  settings: <SettingsIcon />,
  shoppingBag: <ShoppingBagIcon />,
  star: <StarIcon />,
  sun: <SunIcon />,
  thumbsUp: <ThumbsUpIcon />,
  user: <UserIcon />,
  watch: <WatchIcon />,
  wifi: <WifiIcon />,
  x: <XIcon />,
  zoomIn: <ZoomInIcon />,
  thumbsDown: <ThumbsDownIcon />,
  wind: <WindIcon />,
};

export const getIconElement = (iconIdentifier: string) => {
  return iconMapping[iconIdentifier] || null;
};
